// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace PoCStarterTemplate.Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fff1ae44-c101-4b6c-b417-bf3df4ba7e89"),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$11$NgSnpDYhRUi/aDft.7.T7uBGCl/B1dOp1CNAyYjy0zfbic75cs8SW",
                            Phone = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("5d533b96-5fae-4147-b16b-c78eda4c3078"),
                            Email = "user@user.com",
                            Name = "User",
                            Password = "$2a$11$eCDWs7kKK3W/245SitYLz..wghxOWSU3By6sS60CMYGb3PfPWOXZe",
                            Phone = "1234567891"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
